In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [15]:
dataset = pd.read_excel('./第4题最终数据.xlsx')
X = dataset.iloc[:, 0 : 8].values
print(X)
y = dataset.iloc[:, -1].values
print(y)

[[34.  2.  5. ...  3. 13.  9.]
 [33.  2.  5. ...  0.  0.  3.]
 [37.  2.  5. ...  4.  8.  9.]
 ...
 [31.  2.  5. ...  0.  3.  1.]
 [27.  2.  3. ...  1. 10.  5.]
 [32.  2.  5. ... 10. 10.  6.]]
[4 2 2 4 2 2 3 3 4 2 4 3 2 2 4 2 2 3 2 4 2 3 4 4 2 2 3 3 4 2 4 2 4 2 2 3 4
 4 3 2 3 4 2 4 4 3 4 2 4 4 3 3 1 2 1 3 2 2 4 2 3 2 2 4 3 2 4 1 2 3 2 4 1 2
 2 4 4 2 2 2 2 1 2 2 1 2 2 2 4 2 2 3 3 2 3 1 2 2 4 2 2 1 4 4 2 4 3 2 3 3 4
 2 2 3 3 4 2 3 4 2 3 4 3 1 4 2 2 4 4 4 4 1 3 2 2 3 4 3 2 4 2 2 2 3 2 1 4 2
 4 2 2 4 3 2 2 4 4 4 2 4 3 1 2 4 4 3 3 3 3 4 3 3 2 2 2 4 4 2 2 2 3 3 3 3 1
 4 3 2 2 3 3 3 3 4 4 4 2 4 3 2 2 2 4 4 3 4 4 2 2 2 2 3 4 3 2 3 3 2 4 4 4 3
 3 3 2 2 1 3 1 4 3 2 4 1 4 1 3 3 1 4 2 2 4 4 3 4 4 3 4 2 4 4 4 3 3 4 4 4 1
 4 2 3 4 3 2 1 1 3 4 3 1 4 3 4 4 3 4 3 1 3 4 2 4 3 3 4 1 3 4 3 1 2 4 4 4 3
 4 2 3 4 3 1 4 2 4 1 4 3 3 2 1 3 2 4 2 2 2 2 4 1 4 2 3 2 1 2 2 3 3 2 2 2 2
 2 2 4 2 1 1 2 2 1 4 2 3 3 2 2 2 3 2 3 2 4 4 2 2 2 4 4 1 2 4 4 2 4 1 2 3 2
 4 4 2 1 4 4 2 2 3 3 3 2 3 4 4 3 4 4 3]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
y_pred

array([4, 3, 2, 2, 4, 4, 4, 1, 2, 2, 4, 3, 2, 2, 1, 2, 2, 3, 2, 1, 2, 4,
       2, 1, 2, 3, 2, 2, 2, 1, 4, 1, 4, 4, 1, 2, 2, 2, 4], dtype=int64)

In [21]:
y_test

array([1, 4, 2, 4, 3, 3, 4, 4, 2, 2, 2, 4, 3, 1, 4, 2, 2, 3, 3, 1, 2, 2,
       4, 4, 2, 4, 4, 2, 2, 3, 1, 4, 2, 4, 3, 2, 3, 2, 4], dtype=int64)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)
ac

0.41025641025641024

In [23]:
y_train

array([4, 4, 3, 2, 4, 3, 3, 2, 2, 2, 3, 2, 2, 4, 4, 2, 2, 2, 3, 2, 1, 3,
       2, 1, 2, 2, 2, 2, 2, 2, 3, 4, 3, 3, 2, 2, 3, 3, 2, 3, 2, 4, 3, 2,
       2, 4, 2, 4, 4, 1, 2, 3, 1, 2, 4, 1, 2, 3, 3, 1, 3, 2, 4, 2, 3, 3,
       2, 4, 4, 1, 3, 4, 2, 3, 4, 4, 2, 2, 4, 4, 2, 2, 1, 2, 4, 2, 3, 3,
       3, 2, 3, 4, 3, 2, 4, 3, 2, 2, 2, 4, 3, 3, 4, 4, 4, 3, 2, 1, 1, 2,
       2, 2, 2, 2, 3, 2, 2, 2, 4, 3, 3, 3, 3, 3, 4, 3, 4, 4, 2, 3, 4, 3,
       3, 2, 4, 3, 4, 1, 3, 2, 2, 4, 4, 4, 2, 2, 3, 3, 3, 3, 4, 3, 3, 4,
       2, 4, 4, 4, 4, 2, 2, 3, 3, 2, 4, 2, 4, 2, 1, 3, 4, 3, 3, 4, 3, 3,
       2, 1, 2, 3, 4, 4, 1, 2, 2, 2, 4, 2, 4, 3, 2, 3, 4, 3, 2, 4, 4, 4,
       3, 2, 2, 4, 2, 3, 1, 1, 4, 2, 4, 3, 4, 4, 3, 2, 2, 2, 1, 3, 4, 4,
       2, 2, 1, 4, 3, 2, 3, 3, 2, 1, 3, 1, 2, 1, 4, 4, 4, 4, 1, 3, 2, 3,
       3, 2, 1, 3, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 3, 4, 1, 2, 4,
       3, 4, 2, 3, 3, 4, 3, 3, 1, 2, 4, 4, 4, 1, 4, 2, 2, 3, 2, 3, 2, 2,
       2, 2, 4, 3, 2, 4, 4, 4, 3, 2, 2, 4, 1, 4, 3,

In [24]:
y_pred = classifier.predict(X_train)
y_pred

array([2, 2, 3, 4, 2, 2, 1, 2, 1, 4, 3, 3, 2, 4, 1, 2, 2, 2, 3, 2, 3, 3,
       2, 1, 2, 1, 2, 2, 2, 2, 2, 4, 2, 3, 2, 1, 3, 1, 2, 3, 2, 2, 3, 2,
       2, 4, 2, 4, 2, 1, 1, 4, 1, 1, 4, 4, 2, 3, 2, 3, 3, 2, 2, 2, 3, 3,
       3, 4, 2, 1, 3, 2, 2, 2, 4, 2, 2, 2, 1, 4, 2, 2, 1, 2, 4, 2, 3, 2,
       3, 2, 3, 2, 2, 1, 2, 3, 2, 3, 4, 2, 1, 2, 2, 4, 2, 3, 2, 3, 3, 2,
       2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 1, 3, 3, 3, 4, 2, 4, 4, 2, 3, 1, 3,
       4, 2, 4, 3, 3, 1, 2, 2, 4, 2, 4, 3, 1, 2, 4, 3, 3, 3, 2, 2, 3, 2,
       2, 1, 1, 4, 4, 2, 3, 3, 1, 3, 3, 1, 3, 2, 1, 1, 2, 1, 1, 2, 1, 3,
       2, 1, 2, 2, 4, 4, 1, 2, 2, 2, 4, 2, 4, 4, 2, 1, 4, 3, 2, 2, 4, 4,
       4, 1, 2, 2, 2, 3, 1, 1, 2, 2, 4, 2, 2, 4, 3, 2, 2, 2, 1, 1, 4, 2,
       2, 2, 1, 4, 3, 1, 2, 3, 2, 1, 1, 4, 2, 1, 3, 4, 1, 1, 1, 1, 2, 1,
       3, 2, 2, 3, 2, 3, 1, 2, 2, 4, 4, 1, 2, 1, 2, 2, 4, 2, 1, 2, 2, 4,
       3, 2, 4, 3, 2, 1, 1, 3, 1, 2, 3, 2, 4, 2, 4, 2, 2, 3, 2, 4, 3, 4,
       3, 3, 4, 2, 2, 2, 2, 2, 3, 2, 2, 1, 1, 4, 1,

In [25]:
ac = accuracy_score(y_train, y_pred)
ac

0.5914285714285714

In [26]:
new_predict = pd.read_excel('./问题2预测数据.xlsx')
new_predict

母亲年龄  婚姻状况  教育程度  妊娠时间（周数）  分娩方式  CBTS  EPDS  HADS
0     29     2     4      40.0     1     7    15    12
1     29     2     3      42.0     1     9    14    12
2     23     2     2      38.5     1     7    12     7
3     27     2     3      36.3     1     8     4     5
4     36     2     4      39.0     1     6     6     8
5     30     2     5      41.2     1     5     8     5
6     28     2     2      40.6     1     8    11     9
7     32     2     5      37.0     1     3     6     7
8     28     2     5      38.0     1     7    11     5
9     31     2     4      42.0     1     4     5     8
10    25     2     2      40.5     1    16    22    15
11    27     2     5      40.4     1     4     6    10
12    33     2     5      39.0     1     6     6     4
13    25     2     3      39.0     1     0     4     5
14    28     2     2      41.0     1     9     6     5
15    31     2     3      39.5     1     1     4     4
16    26     2     2      37.0     1     4     9    14
17    26     2     5      39.0     1     0     3     3
18    27     2     5      41.2     1     0     0     4
19    31     2     5      38.0     1     3     7     7